add home-path input for GH runners using DynamicUser
When a GitHub runner is running in Systemd serivce context that is using
DynamicUser=true setting the os.userInfo().homedir call returns /(root).

This happens because the Node call uses libuv which calls getpwuid() that
uses the NSS(Name Service Switch) which provide home path from /etc/passwd.

Because of this the action fails with error like this:

Error: ENOENT: no such file or directory, mkdir '//.ssh'

Allowing users to override it is the simplest fix, for example like this:

home-path: $HOME

Signed-off-by: Jakub Sokołowski <jakub@status.im>